language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install .
script:
  - python -m pytest
jobs:
  include:
    - stage: doc
      script: 
        - pip install sphinx>=2.0
        - make html
      python: 3.7
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
