name: PyTest

on: [push]

jobs:
  set_version:
    # If the head commit message contains the string ':tag-as:<TAG>'
    if: "contains( github.event.head_commit.message, ':tag-as:')"
    runs-on: ubuntu-latest
    env:
      GH_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps: 
      - uses: actions/checkout@v2
      - name: Read version
        run: echo "::set-env name=VERSION::$( echo $GH_COMMIT_MESSAGE | sed -E 's/.*:tag-as:([^ ]+).*/\1/' )"
      - name: Change version
        run: |
          sed -i -E 's/__version__=".+"/__version__="'${VERSION}'"/' src/memoclass/__init__.py
          sed -i -E 's/version=".+"/version="'${VERSION}'"/' setup.py
      - name: Commit changes
        run: |
          git config --global user.name "Jon Burr"
          git config --global user.email "jon.burr.gh@gmail.com"
          git commit -am "AUTOCOMMIT: Update version number to ${VERSION}"
          git tag -a ${VERSION} -m "Auto-tagging version ${VERSION}"
          git push
  build:
    needs: set_version
    if: always()
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

  deploy:
    if: "contains( github.event.head_commit.message, ':deploy-pypi:')"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        pip install .
    - name: Build distribution
      run: python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
